// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'headerContainer': string;
  'nav': string;
}
export const cssExports: CssExports;
export default cssExports;
