// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'button_filled': string;
  'button_outlined': string;
}
export const cssExports: CssExports;
export default cssExports;
